# Generated by Django 2.0 on 2018-11-26 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newstitle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstitle',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newstitle',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
