# Generated by Django 2.0 on 2018-11-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstitle', '0003_newstitle_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstitle',
            old_name='auther',
            new_name='author',
        ),
    ]
